export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-zinc-800">
      <h1 className="text-3xl font-bold mb-6">Disclaimer – worklesslab.io</h1>
      <p className="mb-6 text-sm text-zinc-500">Last updated: 19 November 2025</p>

      <p className="mb-6">
        The information and tools provided on https://worklesslab.io (the "Website") are intended for general informational and experimental purposes only.
      </p>

      <p className="mb-6">
        By using the Website and any tools or services provided through it, you agree to this Disclaimer.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">1. No Professional Advice</h2>
      <p className="mb-4">
        The Website does not provide financial, legal, tax, investment, or any other professional advice.
      </p>
      <p className="mb-2">Any calculations, estimates, or results generated by our tools (including but not limited to living cost calculators, subscription cost calculators, and other utilities) are:</p>
      <ul className="list-disc ml-5 space-y-2 mb-4">
        <li>Simplified models</li>
        <li>Based on the data you input</li>
        <li>Not guaranteed to be accurate, complete, or suitable for your specific situation</li>
      </ul>
      <p className="mb-4">
        You should always do your own research and, where appropriate, consult a qualified professional before making decisions based on any information obtained from the Website.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">2. No Guarantees</h2>
      <p className="mb-2">We make no guarantees regarding:</p>
      <ul className="list-disc ml-5 space-y-2 mb-4">
        <li>The accuracy, reliability, or completeness of any content or tool outputs</li>
        <li>The results you may achieve by using the Website</li>
        <li>The availability or continuity of the Services</li>
      </ul>
      <p className="mb-4">Your use of the Website and tools is at your own risk.</p>

      <h2 className="text-xl font-semibold mt-6 mb-2">3. External Links</h2>
      <p className="mb-4">
        The Website may contain links to external websites or services that are not provided or maintained by us.
      </p>
      <p className="mb-4">
        We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on external websites. We are not responsible for the content or practices of any third-party sites.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">4. Advertising and Affiliates</h2>
      <p className="mb-4">
        The Website may display advertisements, including but not limited to Google AdSense or other networks.
      </p>
      <p className="mb-4">
        We do not control which specific ads are shown and do not endorse any products or services advertised unless explicitly stated.
      </p>
      <p className="mb-4">
        If, in the future, we include affiliate links or sponsored content, we will make reasonable efforts to disclose such relationships clearly.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">5. Limitation of Liability</h2>
      <p className="mb-2">To the fullest extent permitted by law, worklesslab, its owners, contributors, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in connection with:</p>
      <ul className="list-disc ml-5 space-y-2 mb-4">
        <li>Your use of the Website or tools</li>
        <li>Your reliance on any information or results provided</li>
        <li>Any errors, omissions, interruptions, or delays in the Services</li>
      </ul>

      <h2 className="text-xl font-semibold mt-6 mb-2">6. Changes to This Disclaimer</h2>
      <p className="mb-4">
        We may update this Disclaimer from time to time. When we do, we will revise the "Last updated" date at the top of this page.
      </p>
      <p className="mb-4">
        Your continued use of https://worklesslab.io after any changes constitutes acceptance of the updated Disclaimer.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">7. Contact Us</h2>
      <p className="mb-2">If you have any questions about this Disclaimer, please contact us at:</p>
      <p className="mb-2">
        Email: <a className="underline text-blue-600" href="mailto:yoyo.in.moomoo@gmail.com">yoyo.in.moomoo@gmail.com</a>
      </p>
      <p className="mb-4">
        Website: <a className="underline text-blue-600" href="https://worklesslab.io" target="_blank" rel="noopener noreferrer">https://worklesslab.io</a>
      </p>
    </main>
  );
}
