export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-zinc-800">
      <h1 className="text-3xl font-bold mb-6">Terms of Service – worklesslab.io</h1>
      <p className="mb-6 text-sm text-zinc-500">Last updated: 19 November 2025</p>

      <p className="mb-6">
        These Terms of Service ("Terms") govern your access to and use of https://worklesslab.io (the "Website") and any tools, services, or content provided through it (collectively, the "Services").
      </p>

      <p className="mb-6">
        By accessing or using the Services, you agree to be bound by these Terms. If you do not agree with these Terms, please do not use the Website or Services.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">1. Use of the Services</h2>

      <h3 className="text-lg font-semibold mt-4 mb-2">1.1. Eligibility</h3>
      <p className="mb-4">
        You may use the Services only if you are capable of forming a binding contract and are not prohibited from using the Services under applicable law.
      </p>

      <h3 className="text-lg font-semibold mt-4 mb-2">1.2. Personal and non-commercial use</h3>
      <p className="mb-4">
        Unless otherwise explicitly stated, the Services are provided for your personal and non-commercial use. You may not resell, redistribute, or exploit the Services for commercial purposes without our prior written consent.
      </p>

      <h3 className="text-lg font-semibold mt-4 mb-2">1.3. Accuracy of input data</h3>
      <p className="mb-4">
        Some tools on the Website rely on data you provide (e.g., costs, amounts, and other numerical inputs). You are responsible for the accuracy of the data you enter. We do not guarantee that any results, estimates, or outputs are accurate, complete, or suitable for any particular purpose.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">2. No Professional Advice</h2>
      <p className="mb-4">
        The information and tools provided on https://worklesslab.io are for general informational and experimental purposes only and do not constitute financial, legal, tax, or professional advice.
      </p>
      <p className="mb-4">
        You should not rely solely on the results generated by the Services to make important decisions. Always consider consulting a qualified professional before making financial or other decisions.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">3. Intellectual Property</h2>

      <h3 className="text-lg font-semibold mt-4 mb-2">3.1. Ownership</h3>
      <p className="mb-4">
        All content on the Website, including but not limited to text, code, design, and logos, is owned by worklesslab or its licensors and is protected by applicable intellectual property laws.
      </p>

      <h3 className="text-lg font-semibold mt-4 mb-2">3.2. Limited license</h3>
      <p className="mb-2">We grant you a limited, non-exclusive, non-transferable, and revocable license to use the Services strictly in accordance with these Terms.</p>
      <p className="mb-2">You may not:</p>
      <ul className="list-disc ml-5 space-y-2 mb-4">
        <li>Copy, modify, distribute, or create derivative works based on the Services</li>
        <li>Reverse engineer or attempt to extract source code, except as permitted by law</li>
        <li>Remove or alter any copyright, trademark, or other proprietary notices</li>
      </ul>

      <h2 className="text-xl font-semibold mt-6 mb-2">4. User Conduct</h2>
      <p className="mb-2">When using the Services, you agree not to:</p>
      <ul className="list-disc ml-5 space-y-2 mb-4">
        <li>Use the Services for any unlawful purpose</li>
        <li>Attempt to gain unauthorized access to any part of the Website or systems</li>
        <li>Interfere with or disrupt the operation of the Services</li>
        <li>Upload or transmit malicious code, viruses, or harmful content</li>
      </ul>
      <p className="mb-4">
        We reserve the right to suspend or terminate your access to the Services if we reasonably believe that you have violated these Terms.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">5. Third-Party Services and Links</h2>
      <p className="mb-4">
        The Website may contain links to third-party websites, services, or advertisements that are not owned or controlled by us.
      </p>
      <p className="mb-4">
        We are not responsible for the content, policies, or practices of any third-party websites or services. Your use of third-party sites is at your own risk.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">6. Disclaimer of Warranties</h2>
      <p className="mb-4">
        The Services are provided on an "AS IS" and "AS AVAILABLE" basis.
      </p>
      <p className="mb-2">To the fullest extent permitted by law, we disclaim all warranties, express or implied, including but not limited to:</p>
      <ul className="list-disc ml-5 space-y-2 mb-4">
        <li>Implied warranties of merchantability, fitness for a particular purpose, and non-infringement</li>
        <li>Any warranty that the Services will be uninterrupted, error-free, secure, or free of harmful components</li>
        <li>Any warranty as to the accuracy, reliability, or completeness of any information or results provided by the Services</li>
      </ul>

      <h2 className="text-xl font-semibold mt-6 mb-2">7. Limitation of Liability</h2>
      <p className="mb-2">To the maximum extent permitted by law, worklesslab, its owners, contributors, and affiliates shall not be liable for any indirect, incidental, consequential, special, or punitive damages, including but not limited to:</p>
      <ul className="list-disc ml-5 space-y-2 mb-4">
        <li>Loss of profits</li>
        <li>Loss of data</li>
        <li>Business interruption</li>
      </ul>
      <p className="mb-4">
        arising out of or in connection with your use of, or inability to use, the Services.
      </p>
      <p className="mb-4">
        Our total aggregate liability for any claim arising out of or relating to the Services shall not exceed the amount you paid (if any) for using the Services in the 3 months preceding the event giving rise to the claim.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">8. Changes to the Services</h2>
      <p className="mb-4">
        We may modify, suspend, or discontinue any part of the Services at any time, with or without notice. We are not liable to you or any third party for any modification, suspension, or discontinuation of the Services.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">9. Changes to These Terms</h2>
      <p className="mb-4">
        We may update these Terms from time to time. When we do, we will revise the "Last updated" date at the top of this page.
      </p>
      <p className="mb-4">
        Your continued use of https://worklesslab.io after any changes constitutes acceptance of the updated Terms.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">10. Governing Law</h2>
      <p className="mb-4">
        These Terms shall be governed by and construed in accordance with the laws applicable in your jurisdiction, without regard to its conflict of law principles.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">11. Contact Us</h2>
      <p className="mb-2">If you have any questions about these Terms, please contact us at:</p>
      <p className="mb-2">
        Email: <a className="underline text-blue-600" href="mailto:yoyo.in.moomoo@gmail.com">yoyo.in.moomoo@gmail.com</a>
      </p>
      <p className="mb-4">
        Website: <a className="underline text-blue-600" href="https://worklesslab.io" target="_blank" rel="noopener noreferrer">https://worklesslab.io</a>
      </p>
    </main>
  );
}
